#!/bin/bash

set -e

# Flatpak
if [ "$1" = "flatpak" ]; then
    # Setup PGP
    echo "${PGP_PASSWORD}" | base64 -d >'/tmp/pgp-pass'
    mkdir -p "${HOME}/.gnupg"
    cat >"${HOME}/.gnupg/gpg.conf" <<EOT
yes
passphrase-file /tmp/pgp-pass
pinentry-mode loopback
EOT

    echo "${PGP_KEY}" | base64 -d >'/tmp/private.pgp'
    gpg --import /tmp/private.pgp

    # Prepare build environment
    mkdir -p /dst/{repo,bundle}
    gpg --output /tmp/repo.asc --armor --export

    # Install dependencies
    dnf install -y flatpak-builder
    flatpak remote-add --if-not-exists 'flathub' 'https://flathub.org/repo/flathub.flatpakrepo'
    flatpak install -y 'flathub' "org.gnome.Platform//44" "org.gnome.Sdk//44" "org.freedesktop.Sdk.Extension.golang//21.08"

    # Build repo
    flatpak-builder -y --gpg-sign="${PGP_ID}" --repo='/dst/repo' --force-clean "build-dir" "com.pojtinger.felicitas.vintangle.yaml"
    echo "[Flatpak Repo]
Title=Vintangle Flatpak repo
Url=https://pojntfx.github.io/vintangle
Homepage=https://github.com/pojntfx/vintangle
Description=Flatpaks for Vintangle
GPGKey=$(base64 -w 0 /tmp/repo.asc)
" >/dst/repo/vintangle.flatpakrepo

    # Export bundle
    flatpak --gpg-sign="${PGP_ID}" build-bundle '/dst/repo' "/dst/bundle/com.pojtinger.felicitas.vintangle.flatpak" "com.pojtinger.felicitas.vintangle"

    exit 0
fi
