#!/bin/bash

set -e

# Flatpak
if [ "$1" = "flatpak" ]; then
    # Install native dependencies
    dnf install -y flatpak-builder

    # Setup Flatpak
    flatpak remote-add --if-not-exists "flathub" "https://flathub.org/repo/flathub.flatpakrepo"

    # Setup GPG
    echo "${GPG_KEY_PASSWORD}" | base64 -d >"/tmp/gpg-pass"
    mkdir -p "${HOME}/.gnupg"
    cat >"${HOME}/.gnupg/gpg.conf" <<EOT
yes
passphrase-file /tmp/gpg-pass
pinentry-mode loopback
EOT
    echo "${GPG_KEY_CONTENT}" | base64 -d >"/tmp/private.gpg"
    gpg --import "/tmp/private.gpg"
    gpg --output "/tmp/public.asc" --armor --export

    # Setup repos
    mkdir -p out/repositories/unstable
    echo "[Flatpak Repo]
Title=Unstable Vintangle Flatpak repo
Url=https://pojntfx.github.io/vintangle/flatpak/unstable/
Homepage=https://github.com/pojntfx/vintangle/
Description=Synchronized torrent streaming for distributed watch parties (unstable builds).
GPGKey=$(base64 -w 0 /tmp/public.asc)
" >"out/repositories/unstable/vintangle.flatpakrepo"

    # Generate dependencies and build
    for ARCH in "x86_64"; do
        flatpak install -y --arch="${ARCH}" "org.gnome.Platform//42" "org.gnome.Sdk//42" "org.freedesktop.Sdk.Extension.golang//21.08"
        flatpak-builder -y --arch="${ARCH}" --gpg-sign="${GPG_KEY_ID}" --repo="out/repositories/unstable" --force-clean "build-dir" "com.pojtinger.felicitas.vintangle.yaml"
        flatpak -y --arch="${ARCH}" --gpg-sign="${GPG_KEY_ID}" build-bundle "out/repositories/unstable" "out/com.pojtinger.felicitas.vintangle.yaml.linux-${ARCH}.flatpak" "com.pojtinger.felicitas.vintangle"
    done

    # Setup stable repo
    cp -r out/repositories/unstable out/repositories/stable
    echo "[Flatpak Repo]
Title=Stable Vintangle Flatpak repo
Url=https://pojntfx.github.io/vintangle/flatpak/stable/
Homepage=https://github.com/pojntfx/vintangle/
Description=Synchronized torrent streaming for distributed watch parties (stable builds).
GPGKey=$(base64 -w 0 /tmp/public.asc)
" >"out/repositories/stable/vintangle.flatpakrepo"

    exit 0
fi
